version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      # Run your bash script
      - run:
          name: Run Bash Script
          command: |
            #!/bin/bash
            echo "Running bash script"
            ./script/reposclone.sh

      # Add additional steps as needed
