version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout

      - run:
          name: Install jq and expect
          command: |
            sudo apt-get update
            sudo apt-get install -y jq expect

      - run:
          name: Clone repositories
          command: |
            # Replace with your GitHub username and organization name
            GITHUB_USERNAME="joshil-connectbase"
            ORGANIZATION_NAME="Connected2FiberTeam"
            # Replace with your personal access token (PAT)
            # Generate one at https://github.com/settings/tokens
            ACCESS_TOKEN="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"
            # API endpoint to fetch repositories
            API_URL="https://api.github.com/orgs/${ORGANIZATION_NAME}/repos"
            # Function to fetch repositories using GitHub API
            function fetch_repositories() {
              local page="$1"
              local repos=$(curl -s -H "Authorization: token ${ACCESS_TOKEN}" "${API_URL}?page=${page}&per_page=100")
              local repos_count=$(echo "${repos}" | jq length)
              if [[ "${repos_count}" -eq 0 ]]; then
                echo "No repositories found."
                return
              fi
              for ((i=0; i<repos_count; i++)); do
                local repo_name=$(echo "${repos}" | jq -r ".[$i] | .name")
                echo "Cloning repository: ${repo_name}"
                if [[ -n "${repo_name}" ]]; then
                  expect -c "
                    spawn git clone --quiet \"https://github.com/${ORGANIZATION_NAME}/${repo_name}.git\" \"${repo_name}\"
                    expect \"Username for 'https://github.com':\" { send \"${GITHUB_USERNAME}\r\" }
                    expect \"Password for 'https://${GITHUB_USERNAME}@github.com':\" { send \"${ACCESS_TOKEN}\r\" }
                    interact
                  "
                fi
              done
            }
            # Create a directory to store the downloaded repositories
            mkdir -p "${ORGANIZATION_NAME}"
            cd "${ORGANIZATION_NAME}"
            # Fetch and clone repositories using pagination
            page=1
            while true; do
              echo "Fetching page: ${page}"
              fetch_repositories "${page}"
              link_header=$(curl -s -I -H "Authorization: token ${ACCESS_TOKEN}" "${API_URL}?page=${page}&per_page=100" | grep -i "Link:" | tr -d '\r')
              if [[ "$link_header" =~ page=([0-9]+) ]]; then
                page="${BASH_REMATCH[1]}"
              else
                break
              fi
            done
            echo "All repositories cloned successfully."
